# Generated by Django 6.0.7 on 2026-09-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='interpretation',
            field=models.TextField(blank=True),
        ),
    ]
