# Generated by Django 6.0.7 on 2026-10-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_interpretation'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_uploads/'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='posts.post'),
        ),
    ]
